title="Open Data Hub Knowledge Graph Portal"

[[tabGroups]]

name="Regular Queries"

[[tabGroups.tabs]]

name="Lodging businesses (limit 500)"
query="""
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?h ?pos ?posLabel ?posColor
WHERE {
  ?h a schema:LodgingBusiness ;
     geo:asWKT ?pos ;
     schema:name ?posLabel ;
     schema:address ?a .
  # ?a schema:postalCode "39100" . # Uncomment for Bolzano only
  FILTER (lang(?posLabel) = 'de')

  # Colors
  OPTIONAL {
    ?h a schema:Campground .
    BIND("chlorophyll,0.5" AS ?posColor) # Green
  }
    OPTIONAL {
    ?h a schema:BedAndBreakfast .
    BIND("viridis,0.1" AS ?posColor) # Purple
  }
  OPTIONAL {
    ?h a schema:Hotel .
    BIND("jet,0.3" AS ?posColor) # Light blue
  }
  OPTIONAL {
    ?h a schema:Hostel .
    BIND("jet,0.8" AS ?posColor) # Red
  }
}
LIMIT 500
"""

[[tabGroups.tabs]]

name="Biggest lodging businesses"
query="""
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX schema: <http://schema.org/>
PREFIX : <http://noi.example.org/ontology/odh#>

SELECT ?pos ?posColor ?bName
      (SUM(?nb) AS ?countRoom)
      (SUM(?maxPersons) AS ?countMaxPersons)
      (CONCAT(?bName, ': ', str(?countRoom), ' accommodations, max ', str(?countMaxPersons), ' guests') AS ?posLabel)
WHERE {
  ?b a schema:LodgingBusiness ;
     schema:name ?bName ;
     geo:asWKT ?pos .

  ?r a schema:Accommodation ;
     schema:containedInPlace ?b ;
     :numberOfUnits ?nb ;
     schema:occupancy [ schema:maxValue ?maxOccupancyPerRoom ] .

  # ?b schema:address [ schema:postalCode "39100" ] # For Bolzano only

  BIND (?nb * ?maxOccupancyPerRoom AS ?maxPersons)
  FILTER (lang(?bName)='en')

  # Colors
  OPTIONAL {
    ?b a schema:Campground .
    BIND("chlorophyll,0.5" AS ?posColor) # Green
  }
  OPTIONAL {
    ?b a schema:BedAndBreakfast .
    BIND("viridis,0.1" AS ?posColor) # Purple
  }
  OPTIONAL {
    ?b a schema:Hotel .
    BIND("jet,0.3" AS ?posColor) # Light blue
  }
  OPTIONAL {
    ?b a schema:Hostel .
    BIND("jet,0.8" AS ?posColor) # Red
  }
}
GROUP BY ?b ?bName ?pos ?posColor
ORDER BY DESC(?countRoom)
LIMIT 50
"""

[[tabGroups.tabs]]
name="Number of lodging businesses"
query="""
PREFIX schema: <http://schema.org/>

SELECT (COUNT(?h) AS ?count)
WHERE {
  ?h a schema:LodgingBusiness
}
"""

[[tabGroups.tabs]]
name="Number of lodging businesses in Bolzano"
query="""
PREFIX schema: <http://schema.org/>

SELECT (COUNT(DISTINCT ?h) AS ?count)
WHERE {
  ?h a schema:LodgingBusiness ;
     schema:address ?a .
  ?a schema:postalCode "39100" .
}
"""

[[tabGroups.tabs]]
name="Ski areas in the region with a custom label"
query="""
PREFIX : <http://noi.example.org/ontology/odh#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX schema: <http://schema.org/>

SELECT ?pos ?posLabel
WHERE {
  ?s a schema:SkiResort ;
     schema:name ?name ;
     geo:asWKT ?pos ;
     schema:geo [ schema:elevation ?maxElevation ] ;
     schema:image ?img ;
     schema:isPartOf ?skiRegion.

  ?skiRegion a :SkiRegion ;
     schema:name ?regionName.

  BIND(concat(
      '<h3>',str(?name),' </h3>',
      ?regionName,
      ', max elevation: ', str(?maxElevation), ' m ',
      '<img src="',str(?img), '" height="300" width="300">'
    ) as ?posLabel)
}
"""

[[tabGroups.tabs]]
name="Food establishments (limit 500)"
query="""
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?e ?pos ?posLabel ?posColor
WHERE {
  ?e a schema:FoodEstablishment ;
     geo:asWKT ?pos ;
     schema:name ?posLabel ;
     schema:address ?a .
  # ?a schema:postalCode "39100" . # Uncomment for Bolzano only
  FILTER (lang(?posLabel) = 'de')

  # Colors (with priority)
  OPTIONAL {
    ?e a schema:Restaurant .
    BIND("jet,0.3" AS ?posColor) # Light blue
  }
  OPTIONAL {
    ?e a schema:BarOrPub .
    BIND("chlorophyll,0.5" AS ?posColor) # Green
  }
  OPTIONAL {
    ?e a schema:Winery .
    BIND("viridis,0.1" AS ?posColor) # Purple
  }
  OPTIONAL {
    ?e a schema:FastFoodRestaurant .
    BIND("jet,0.8" AS ?posColor) # Red
  }
}
LIMIT 500
"""

[[tabGroups.tabs]]
name="Restaurants above 1500 m"
query="""
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?e
       ?pos
       (CONCAT(?name, " (", str(?altitude), " m)") AS ?posLabel)
       ?posColor
WHERE {
  ?e a schema:Restaurant;
     geo:asWKT ?pos ;
     schema:name ?name ;
     schema:geo ?geo .
  ?geo schema:elevation ?altitude .
  FILTER (lang(?name) = 'de')
  FILTER (?altitude >= 1500)
}
"""

[[tabGroups.tabs]]
name="Pizzerias"
query="""
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX : <http://noi.example.org/ontology/odh#>

SELECT ?pos ?posLabel
WHERE {
  ?p a :Pizzeria ;
     geo:asWKT ?pos ;
     schema:name ?posLabel ;
     schema:geo ?geo .
  FILTER (lang(?posLabel) = 'it')
}
"""

[[tabGroups]]

name="Data Quality Queries"

[[tabGroups.tabs]]

name="Lodging businesses without accommodation"
query="""
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX schema: <http://schema.org/>

SELECT ?pos ?posColor ?bName (?bName AS ?posLabel)
WHERE {
  ?b a schema:LodgingBusiness ; schema:name ?bName ; geo:asWKT ?pos .
  MINUS {
     ?r schema:containedInPlace ?b .
     ?r a schema:Accommodation
  }
  FILTER (lang(?bName) = 'en')

  # Colors
  OPTIONAL {
    ?b a schema:Campground .
    BIND("chlorophyll,0.5" AS ?posColor) # Green
  }
  OPTIONAL {
    ?b a schema:BedAndBreakfast .
    BIND("viridis,0.1" AS ?posColor) # Purple
  }
  OPTIONAL {
    ?b a schema:Hotel .
    BIND("jet,0.3" AS ?posColor) # Light blue
  }
  OPTIONAL {
    ?b a schema:Hostel .
    BIND("jet,0.8" AS ?posColor) # Red
  }
}
"""

[[tabGroups.tabs]]

name="Lodging businesses with a non-South Tyrolean postal code"
query="""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?h ?pos ?posLabel ?zip WHERE {
  ?h a schema:LodgingBusiness ; geo:asWKT ?pos ; schema:name ?posLabel ; schema:address ?a .
  ?a schema:postalCode ?zip .
  FILTER (lang(?posLabel)='de').
  FILTER regex(?zip, '^(?!39+)', 'i').
}
"""

[[tabGroups.tabs]]

name="Lodging businesses outside the South-Tyrolean regions' bounding box"
query="""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?h ?pos ?posLabel ?box ?boxColor ?posColor {
?h a schema:LodgingBusiness ; schema:name ?posLabel ; schema:geo [ schema:latitude ?lat ; schema:longitude ?long ] ; geo:asWKT ?pos .
FILTER (?lat < 46.2198 || ?lat > 47.0921 || ?long < 10.3818 || ?long > 12.4779) .
FILTER (lang(?posLabel) = 'de') .
BIND("MULTILINESTRING((10.3818 46.2198, 12.4779 46.2198, 12.4779 47.0921, 10.3818 47.0921, 10.3818 46.2198))"^^geo:wktLiteral AS ?box) .
BIND("jet,0.8" AS ?posColor) .
BIND("jet,0.8" AS ?boxColor) .
}
"""

[[tabGroups.tabs]]

name="Lodging businesses in Bolzano with the wrong German or Italian name"
query="""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?h ?pos ?posLabel ("jet,0.8" AS ?posColor) WHERE {
  ?h a schema:LodgingBusiness ; geo:asWKT ?pos ; schema:name ?name ; schema:address ?a .
  ?a schema:addressLocality ?deCity, ?itCity ; schema:postalCode "39100" .
  FILTER ((lang(?name) = 'de') && (lang(?deCity) = 'de') && (lang(?itCity) = 'it')
    && ((lcase(str(?itCity)) != "bolzano") || (lcase(str(?deCity)) != "bozen")))

  BIND(concat(?name,'<hr/>de: ',?deCity, '<hr/> it: ',?itCity) AS ?posLabel)
}
"""
