version: '3.4'

services:
  app:
    image: ${DOCKER_IMAGE_APP}:${DOCKER_TAG_APP}
    restart: unless-stopped
    env_file: .env
    environment:
      - ONTOLOGY_FILE=/opt/ontop/input/odh.ttl
      - MAPPING_FILE=/opt/ontop/input/odh.obda
      - PROPERTIES_FILE=/opt/ontop/input/odh.docker.properties
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./src:/opt/ontop/src
    ports:
      - "${DOCKER_SERVER_PORT}:8080"
