version: '3.4'

services:
  ontop:
    build:
      context: ./
      dockerfile: infrastructure/docker/ontop/Dockerfile
      target: dev
    env_file: .env
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/odh.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/odh.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/odh.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/odh.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      FLYWAY_PLACEHOLDERS_ORIGINAL_HOST_IP: "master-db"
      FLYWAY_PLACEHOLDERS_ORIGINAL_DB: "tourismuser"
      FLYWAY_PLACEHOLDERS_ORIGINAL_USER: "vkgreplicate"
      FLYWAY_PLACEHOLDERS_ORIGINAL_PASSWORD: "Azerty"
      FLYWAY_PLACEHOLDERS_SUBSCRIPTION_NAME: "vkgsubscription_test"
      FLYWAY_URL: "jdbc:postgresql://slave-db/tourismuser"
      FLYWAY_USER: "tourismuser"
      FLYWAY_PASSWORD: "postgres2"
      EXTRA_FLYWAY_OPTIONS: "-mixed=true"
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./src:/opt/ontop/src
    entrypoint: ["/wait-for-it.sh","master-db:5432","--timeout=0","--strict", "--", "/entrypoint.sh"]
  nginx:
    build:
      context: ./
      dockerfile: infrastructure/docker/nginx/Dockerfile
    env_file: .env
    ports:
      - "${SERVER_PORT}:80"
  master-db:
    image: ontopicvkg/odh-tourism-db:master
    environment:
      - POSTGRES_USER=tourismuser
      - POSTGRES_PASSWORD=postgres2
  slave-db:
    image: postgres:12
    shm_size: 1g
    ports:
      - "${MAPPED_POSTGRES_PORT}:5432"
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      - POSTGRES_USER=tourismuser
      - POSTGRES_PASSWORD=postgres2
