version: '3.4'

services:
  ontop:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: dev
    restart: unless-stopped
    env_file: .env
    environment:
      - ONTOP_ONTOLOGY_FILE=/opt/ontop/input/odh.ttl
      - ONTOP_MAPPING_FILE=/opt/ontop/input/odh.obda
      - ONTOP_PROPERTIES_FILE=/opt/ontop/input/odh.docker.properties
      - ONTOP_PORTAL_FILE=/opt/ontop/input/odh.portal.toml
      - ONTOP_CORS_ALLOWED_ORIGINS=*
      - ONTOP_DEV_MODE=true
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./src:/opt/ontop/src
  nginx:
    build: 
      context: caching/nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - "${DOCKER_SERVER_PORT}:80"
