version: "3.4"

services:
  ontop:
    image: ${DOCKER_IMAGE_ONTOP}:${DOCKER_TAG}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/odh.ttl
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/catalog-v001.xml
      ONTOP_MAPPING_FILE: /opt/ontop/input/odh.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/odh.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/odh.portal.toml
      ONTOP_PREDEFINED_CONFIG: /opt/ontop/input/predefined/predefined.json
      ONTOP_PREDEFINED_QUERIES: /opt/ontop/input/predefined/queries.toml
      ONTOP_CONTEXTS: /opt/ontop/input/predefined/contexts.json
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
  ontop-guest:
    image: ${DOCKER_IMAGE_ONTOP}:${DOCKER_TAG}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/odh.ttl
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/catalog-v001.xml
      ONTOP_MAPPING_FILE: /opt/ontop/input/odh_guest.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/odh.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/odh_guest.portal.toml
      ONTOP_PREDEFINED_CONFIG: /opt/ontop/input/predefined/predefined.json
      ONTOP_PREDEFINED_QUERIES: /opt/ontop/input/predefined/queries.toml
      ONTOP_CONTEXTS: /opt/ontop/input/predefined/contexts.json
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
  nginx:
    image: ${DOCKER_IMAGE_NGINX}:${DOCKER_TAG}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "${SERVER_PORT}:80"
  oauth2:
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
    env_file:
      - .env
    environment:
      OAUTH2_PROXY_PROVIDER: "keycloak"
      OAUTH2_PROXY_CLIENT_ID: "$KEYCLOAK_CLIENT_ID"
      OAUTH2_PROXY_CLIENT_SECRET: "$KEYCLOAK_CLIENT_SECRET"
      OAUTH2_PROXY_COOKIE_SECRET: "$OAUTH2_COOKIE_SECRET"
      OAUTH2_PROXY_LOGIN_URL: "$KEYCLOAK_REALM/protocol/openid-connect/auth"
      OAUTH2_PROXY_REDEEM_URL: "$KEYCLOAK_REALM/protocol/openid-connect/token"
      OAUTH2_PROXY_VALIDATE_URL: "$KEYCLOAK_REALM/protocol/openid-connect/userinfo"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_EMAIL_DOMAINS: "${OAUTH2_ALLOWED_EMAIL_DOMAINS}"
      # development-only
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:${SERVER_PORT}/oauth2/callback"
