version: "3.4"

services:
  ontop:
    image: ${DOCKER_IMAGE_ONTOP}:${DOCKER_TAG}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/odh.ttl
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/catalog-v001.xml
      ONTOP_MAPPING_FILE: /opt/ontop/input/odh.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/odh.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/odh.portal.toml
      ONTOP_PREDEFINED_CONFIG: /opt/ontop/input/predefined/predefined.json
      ONTOP_PREDEFINED_QUERIES: /opt/ontop/input/predefined/queries.toml
      ONTOP_CONTEXTS: /opt/ontop/input/predefined/contexts.json
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
  ontop-guest:
    image: ${DOCKER_IMAGE_ONTOP}:${DOCKER_TAG}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/odh.ttl
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/catalog-v001.xml
      ONTOP_MAPPING_FILE: /opt/ontop/input/odh_guest.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/odh.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/odh_guest.portal.toml
      ONTOP_PREDEFINED_CONFIG: /opt/ontop/input/predefined/predefined.json
      ONTOP_PREDEFINED_QUERIES: /opt/ontop/input/predefined/queries.toml
      ONTOP_CONTEXTS: /opt/ontop/input/predefined/contexts.json
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
  nginx:
    image: ${DOCKER_IMAGE_NGINX}:${DOCKER_TAG}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "${SERVER_PORT}:80"
  oauth2:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.0.1
    env_file: .env
    command:
      [
        "--provider=keycloak",
        "--login-url=${KEYCLOAK_REALM_URL}/protocol/openid-connect/auth",
        "--redeem-url=${KEYCLOAK_REALM_URL}/protocol/openid-connect/token",
        "--profile-url=${KEYCLOAK_REALM_URL}/protocol/openid-connect/userinfo",
        "--allowed-group=${KEYCLOAK_ALLOWED_GROUPS}",
        "--scope=openid",
        "--email-domain=*",
        "--http-address=0.0.0.0:4180",
      ]
    environment:
      OAUTH2_PROXY_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}"
      OAUTH2_PROXY_CLIENT_SECRET: "${KEYCLOAK_CLIENT_SECRET}"
      OAUTH2_PROXY_COOKIE_SECRET: "${AUTH_PROXY_COOKIE_SECRET}"
